### ISSUE TITLE
 spring.telegram.client.database-encryption-key

### ISSUE THREAD

**Issue by jackeyprince** [p-vorobyev/spring-boot-starter-telegram#23]
where do i get the spring.telegram.client.database-encryption-key from ？

**Comment by jackeyprince** [comment]
[
    code: 401,
    message: Unauthorized
    queryIdentifier: -972768574
]

**Comment by p-vorobyev** [comment]
> where do i get the spring.telegram.client.database-encryption-key from ？

It's your own secret, you can randomly generate string and save it. The client database will be encrypted with this secret.

**Comment by jackeyprince** [comment]
i do like this   randomly generate string and save it , log is [
code: 401,
message: Unauthorized
queryIdentifier: -972768574
]

**Comment by p-vorobyev** [comment]
When you set `spring.telegram.client.database-encryption-key` it should be the same all the time(like documentation says `If the encryption key is invalid, then an error with code 401 will be returned.`). If you started the client before with another key then you should clean database directory first and reauthorise the client. 

After that you can continue and authorise your client by steps from [readme](https://github.com/p-vorobyev/spring-boot-starter-telegram?tab=readme-ov-file#example). You can see [example in simple-client](https://github.com/p-vorobyev/spring-boot-starter-telegram/blob/master/simple-client/src/main/java/dev/voroby/springframework/telegram/controller/AuthorizationController.java) how to input your authorisation code from telegram.
