### ISSUE TITLE
Error : 400 : Have no access to the user

### ISSUE THREAD

**Issue by 3252152** [p-vorobyev/spring-boot-starter-telegram#25]
[ 1][t 5][1722342274.462772369][MessageEntity.cpp:3822][#1][!Td] Receive wrong user 6410366266: [Error : 400 : Have no access to the user] from server message 857800 in chat -1001528369605 sent by chat 609517172 from get channel difference
﻿

**Comment by p-vorobyev** [comment]
Looks like internal user-manager received an error message from the server and some entities in the chat can no longer be accessed. I think it's just a log message and can be ignored if the client works as expected.
