### ISSUE TITLE
How to achieve high availability

### ISSUE THREAD

**Issue by zcxgsq** [p-vorobyev/spring-boot-starter-telegram#33]
I deployed two, there may be issues.
After one service is started and has been authorized to log in successfully, another service needs to log in again.
So I tried to copy the database files from the first authorized machine to another machine without logging in again, but only when the first machine was not started. When it was started, it would prompt that another program had locked a part of the file and the process could not access it. So I don't know how to solve it

**Comment by p-vorobyev** [comment]
TDLib has a limitation that a database can work only with one running instance at the same time. If you want to run multiple instances, each must have its own independent database directory. For example, you can use the same `api-id`, `api-hash`, `phone` for two instances, but different `device-model` properties(service1, service2, etc). But keep in mind about limitations of the Telegram, it's up to server to restrict your access or ban you(for suspicious activity or for too many clients).

**Comment by p-vorobyev** [comment]
Similar [question](https://github.com/tdlib/td/issues/220).
